### ISSUE TITLE
checkpoints file not working properly,does anyone know what is the problem?

### ISSUE THREAD

**Issue by karimtamer23** [mciepluc/apbi2c_cocotb_example#4]
`from cocotb import simulator
from cocotb.handle import *

checkpoint_hier = []

#this function must be called prior to creating any checkpoint
def get_checkpoint_hier(entity):
    iterator  = simulator.iterate(entity._handle,simulator.OBJECTS)
    while True:
        try:
            ii = simulator.next(iterator)
        except StopIteration:
            break

        hdl = SimHandle(ii, entity._path + "." + simulator.get_name_string(ii))
        
        if ((simulator.get_type(ii) is simulator.MODULE) or
          (simulator.get_type(ii) is simulator.NETARRAY) or
          (simulator.get_type(ii) is simulator.GENARRAY)):
            get_checkpoint_hier(hdl)
        elif simulator.get_type(ii) is simulator.REG:
            checkpoint_hier.append(hdl)
            
    
#returns a created checkpoint
def checkpoint():
    checkpoint_data = {}
    for reg in checkpoint_hier:
        checkpoint_data[reg] = reg.value
    
    return checkpoint_data

#restores a checkpoint
def restore(checkpoint_data):
    for reg in checkpoint_data:
        reg.setimmediatevalue(checkpoint_data[reg])`

This is what i get when i run the simulation :
   Test Failed: test_tree (result was AttributeError)
                                                                                                                     Traceback (most recent call last):
                                                                                                                       File "/home/karim/apbi2c_cocotb_example/tb/test_i2c.py", line 281, in test_tree
                                                                                                                         get_checkpoint_hier(dut)
                                                                                                                       File "/home/karim/apbi2c_cocotb_example/tb/checkpoint.py", line 48, in get_checkpoint_hier
                                                                                                                         iterator  = simulator.iterate(entity._handle,simulator.OBJECTS)
                                                                                                                     AttributeError: module 'cocotb.simulator' has no attribute 'iterate'

**Comment by karimtamer23** [comment]
@mciepluc do you know what might be the problem?

**Comment by mciepluc** [comment]
@karimtamer23 it is a pretty old example, working well with cocotb 1.0 or 1.1, if I remember. I need to review the code to fix it and adjust for the newest cocotb.

**Comment by karimtamer23** [comment]
@mciepluc I suspected that as well.Well,if you find anything that needs to be adjusted to fix it please tell me.
Thanks in advance

**Comment by H0sseinR0stami** [comment]
Hi. Just put this checkpoint code at the beginning of test_i2c.py file.

---------------------------------------------------------------------------------------------------------


CHECKPOINTS_TREE_STRUCTURE = True

checkpoint_hier = []

#this function must be called prior to creating any checkpoint
def get_checkpoint_hier(entity):
   for ii in entity._handle.iterate(simulator.OBJECTS):
    	
      hdl = SimHandle(ii, entity._path + "." + entity._handle.get_name_string())
        
      if ((entity._handle.get_type() is simulator.MODULE) or
          (entity._handle.get_type() is simulator.NETARRAY) or
          (entity._handle.get_type() is simulator.GENARRAY)):
            get_checkpoint_hier(hdl)
      elif entity._handle.get_type() is simulator.REG:
            checkpoint_hier.append(hdl)

**Comment by mciepluc** [comment]
The issue has been fixed
